### ISSUE TITLE
MNIST example cannot run on a local STACKn deployment (--insecure option)

### ISSUE THREAD

**Issue by carmat88** [scaleoutsystems/examples#8]
**Scenario:** a user would like to test Studio quick start tutorial by deploying a local STACKn/develop without the use of a TLS certificate. This means that the STACKn environmental variable `STACKN_SECURE` should be equal to `False` (equivalent to run the stackn cli with the  -`-insecure` flag).

**Behaviour:** Currently `STACKN_SECURE` is by default set to `True` [in the file auth.py](https://github.com/scaleoutsystems/stackn/blob/develop/cli/stackn/auth.py). In the Jupyter notebook `mnist_example_tf_serving.ipynb`, at the current step `In [13]` the line: 

`conf, status = sa.get_token()` will return the following error:

```
Failed to call studio endpoint at: studio.stackn.X.X.X.X.nip.io
Failed to get required config.
```
This is related to [a failed check with keycloak ](https://github.com/scaleoutsystems/stackn/blob/develop/cli/stackn/auth.py#L215)due to `STACKN_SECURE` being set by default to `True` while the setup is actually running locally on a self-signed certificate (generated for example by microk8s).

Similarly, the Jupyter notebook line:
`
res = requests.post('https://tensorflow-serving-mnist-test-qce-3053.studio.safespring-prod.stackn.dev/v1/models/models:predict', json=inp, headers={"Authorization": "Bearer "+conf["STACKN_ACCESS_TOKEN"]})`

would fail unless the post request is being told to use "`verify=False`" (by default is `True`)

**Possible Solution**: 
Change the notebook as follows:

```
# If running locally without a TLS certificate then CHANGE secure and verify variables to False
secure = {"STACKN_SECURE": True}
verify = True
conf, status = sa.get_token(secure)
res = requests.post('URL-here', verify, json=inp, headers={"Authorization": "Bearer "+conf["STACKN_ACCESS_TOKEN"]})
```

**Comment by ahellander** [comment]
Sounds good to me, proceed to implement.

**Comment by carmat88** [comment]
Done via [this commit](https://github.com/scaleoutsystems/examples/commit/423b9a005d6cb14760d38ec19110ff5fcbf703b4)
